Implemented function to resample time series object
openego/eDisGo pull request #269
Opened 2022-07-21 15:10 UTC by maike93he

# Description
Time series object is resampled from hourly to quarter hourly resolution.
Three possible methods to fill missing values
* ffill (see: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ffill.html)
* bfill (see: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.bfill.html)
* interpolate (see: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html)

Fixes #260

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] New and adjusted code is formated using the `pre-commit` hooks
- [x] New and adjusted code includes type hinting now
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-28 07:49 UTC, khelfen commented
Hey :) thank you for the good first version! I have a few requests:

- [ ] Could you make the `freq` an input parameter to the function so that the user can choose if he wants to resample to `"15min"`, `"30min"`, etc.?
- [ ] Could you add basic tests for each resample method?
- [ ] Could you add a wrapper function within the main `EDisGo` class so that you can call this function like `edisgo.resample_timeseries` additionaly of `edisgo.timeseries.resample_timeseries`?
- [ ] (We should maybe add downsampling methods as well later on.)

I merged the current `dev` into your branch so make sure to `git pull` before doing any changes.

2022-07-28 07:51 UTC, khelfen requested changes
Hey :) thank you for the good first version! I have a few requests:

- [x] Please make `freq` an input parameter to the function so that the user can choose if he wants to resample to `"15min"`, `"30min"`, etc.
- [x] Please add basic tests for each resample method
- [x] Please add a wrapper function within the main `EDisGo` class so that you can call this function like `edisgo.resample_timeseries` additionaly of `edisgo.timeseries.resample_timeseries`
- [ ] (We should maybe add downsampling methods as well later on.)

I merged the current `dev` into your branch so make sure to `git pull` before doing any changes.

2022-08-18 08:21 UTC, khelfen approved these changes

2022-09-04 19:14 UTC, birgits commented
I fixed the API doc where you were still using old versions, expanded the docstring a bit and added tests for interpolate and bfill.

2022-09-04 19:15 UTC, merged